language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
before_script:
  - npm install cherrio
  - npm install fs
  - npm install node-powershell
  - npm install ping
  - npm install request
